export const langArr = [
  {
    id: "en",
    homeScreen: { header: "Hello!", buttonLeng: "", buttonFindCity: "Find City" },
    findCityScreen: {
      header: "To home",
      title: "Air condition information by city name:",
      enter: "Enter the name of the locality",
      label: "City",
      btnSend: "Search",
      adress: "Adress:",
      geo: "Geo location:",
      dominant: "Dominant:",
      state: [
        "good",
        "Moderate",
        "Unhealthy for Sensitive Groups",
        "Unhealthy",
        "Very Unhealthy",
        "Hazardous",
      ],
    },
  },
  {
    id: "ru",
    homeScreen: { header: "Привет!", buttonLeng: "", buttonFindCity: "Find City" },
    findCityScreen: {
      header: "Вернуться на главную",
      title: "Информация о состоянии воздуха по названию города:",
      enter: "Введите название населенного пункта",
      label: "Город",
      btnSend: "Поиск",
      adress: "Адресс:",
      geo: "Geo location:",
      dominant: "Доминирующий:",
      state: ["good", "Умеренный", "Нездоровый", "Нездоровый", "Нездоровый", "Нездоровый"],
    },
  },
  {
    id: "ua",
    homeScreen: { header: "Привiт!", buttonLeng: "", buttonFindCity: "Find City" },
    findCityScreen: {
      header: "Повернутись на головну",
      title: "Інформація про стан повітря за назвою міста:",
      enter: "Введіть назву міста",
      label: "Мiсто",
      btnSend: "Пошук",
      adress: "adress",
      geo: "Geo location:",
      dominant: "dominant",
      state: ["good", "", "", ""],
    },
  },
];
